workflows:
  ios-ad-hoc:
    name: DGX Thermal — iOS IPA
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.secfathy.dgxThermal

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios && pod install

      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --target=lib/main.dart \
            --suppress-analytics

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - secfathy@icloud.com
        notify:
          success: true
          failure: true
